[package]
name = "conv"
version = "0.1.0"
authors = ["negamartin"]
edition = "2018"

[dependencies]
osu-db = { path = "..", features = ["ser-de"] }
failure = "0.1"

serde = "1"
ron = "0.4"
serde_json = "1"
